version: '3'
services:
  db:
    image: mariadb
    restart: on-failure
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - db_ahmedosman_dev:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: hasloroot
      MARIADB_USER: ahmosm
      MARIADB_PASSWORD: qwerty
      MARIADB_DATABASE: ahmedosman
    ports:
      - "3306:3306"
volumes:
  db_ahmedosman_dev: